[tasks.rlib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.rlib" ]


[tasks.alib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.alib" ]


[tasks.mkdir]
command = "mkdir"
args = ["./target" ]

[tasks.ci-flow]
dependencies = ["mkdir", "rlib", "alib" ]
