[tasks.rlib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.rlib" ]


[tasks.alib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.alib" ]

[tasks.ci-flow]
dependencies = [ "rlib", "alib" ]
