[tasks.rlib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.rlib" ]


[tasks.alib]
command = "cp"
args = ["./LICENSE.txt", "./target/test.alib" ]


[tasks.mkdir]
command = "mkdir"
args = ["./target" ]

[tasks.ci-flow]
dependencies = ["mkdir", "rlib", "alib", "nightly" ]

[tasks.nightly]
command = "cargo"
toolchain = "nightly-2022-05-19"
args = ["build"]
